#!C:/python27/python.exe
'''
Kenneth Huynh (N18178828)
This program shows to the user the questions and answers for hw00.
'''
from __future__ import print_function
def main():
    print("What is your lecture professor's name?")
    print("Evan Gallagher.")
    print("\n")
    print("What are his office hours?")
    print("After 6:00 pm on Mondays and Wednesdays.")
    print("\n")
    print("Where is his office?")
    print("2 MTC in room 10.010")
    print("\n")
    print("Should you always bring your laptop to the lab?")
    print("Of course you should!")
    print("\n")
    print("What are the dates and times of the midterms?")
    print("March 10, April 14 beginning at 12:30 pm until 2:30 pm.")
    print("\n")
    print("What class period are the midterms given?")
    print("During the common exam period.")
    print("\n")
    print("What day and time is that?")
    print("It's on Tuesdays starting at 12:30.")
    print("\n")
    print("What percentage of your final grade do these count?")
    print("They each are 25% of my final grade.")
    print("\n")
    print("What is the period during which final exams are given?")
    print("Some time between May 8 and May 19.")
    print("\n")
    print("What percentage of your final grade does the final exam count?")
    print("It counts for 35% of my final grade.")
    print("\n")
    print("If you do not take the final exam will you automatically fail the course?")
    print("Yes of course you do!")
    print("\n")
    print("What percentage of your final grade does your lecture attendance and participation count?")
    print("They don't' count towards my final grade.")
    print("\n")
    print("How does it affect your letter grade?")
    print("I can fail the course if I do not meet the requirements.")
    print("\n")
    print("What percentage of your final grade do the labs count?")
    print("They don't' count towards my final grade.")
    print("\n")
    print("How does it affect your letter grade?")
    print("I can fail the course if I do not meet the requirements.")
    print("\n")
    print("What is the minimum number of lectures you must attend to pass this course?")
    print("I must attend at least 21 out of 26 lectures.")
    print("\n")
    print("If you do not meet that minimum number what grade will you get for the course?")
    print("I will receive an F.")
    print("\n")
    print("What is the minimum score in the labs you must attain to pass this course?")
    print("I must earn a minimum score of 200 out of 240 points.")
    print("\n")
    print("If you do not meet that minimum score what grade will you get for the course?")
    print("I will receive an F.")
    print("\n")
    print("Do we accept emailed homework?")
    print("No, all homework must be submitted through NYU classes.")
          
    
if __name__ == '__main__':
    main()
